import re
from typing import List, Optional

from app.domain.job import JobDescription, Requirement
from app.llm.client import LLMClient

class JDAnalyzer:
    """Extract only text that is visibly present in the supplied job description."""

    STOP_WORDS = {
        "and", "the", "with", "for", "such", "as", "that", "this", "should", "have",
        "must", "required", "knowledge", "experience", "familiarity", "job", "role",
        "about", "description", "responsibilities", "requirements", "qualifications",
    }
    HEADING_RE = re.compile(
        r"^(about( the)? job|about us|what we offer|benefits|equal opportunity|"
        r"nice to have|who you are|what you.ll do|"
        r"(minimum|required|basic|desired|preferred|additional|other|key|core|"
        r"technical|essential|primary|general)?\s*"
        r"(responsibilit(y|ies)|requirements?|qualifications?|skills)"
        r")[:\s]*$",
        re.IGNORECASE,
    )
    REQUIREMENT_SIGNALS = (
        "must", "required", "requirement", "qualified", "qualification", "proficien",
        "experience", "years", "degree", "bachelor", "master", "phd", "responsible",
        "responsibilities", "develop", "design", "build", "manage", "lead", "create",
        "implement", "maintain", "analyze", "collaborate", "knowledge of", "ability to",
    )
    PREFERRED_SIGNALS = ("preferred", "nice to have", "optional", "bonus", "plus")

    def __init__(self, llm_client: Optional[LLMClient] = None):
        # Deliberately unused: scoring requirements must be recoverable verbatim
        # from the JD, rather than generated by a model.
        self.llm_client = llm_client

    def extract_keywords_from_text(self, text: str) -> List[str]:
        words = re.findall(r"\\b[A-Za-z0-9+#.-]{2,}\\b", text)
        return list(dict.fromkeys(
            word.strip(".,()") for word in words
            if word.strip(".,()").lower() not in self.STOP_WORDS
        ))

    def _category(self, line: str) -> str:
        lowered = line.lower()
        if any(k in lowered for k in ("degree", "education", "bachelor", "master", "phd")):
            return "qualification"
        if any(k in lowered for k in (
            "responsible", "develop", "design", "build", "manage", "lead", "implement",
            "maintain", "analyze", "collaborate", "create",
        )):
            return "responsibility"
        return "skill"

    def _is_requirement(self, line: str, was_bullet: bool, in_requirement_section: bool) -> bool:
        lowered = line.lower()
        if self.HEADING_RE.match(line) or len(line) < 4:
            return False
        # Bullets under a requirements-like heading are explicit source items.
        return was_bullet or in_requirement_section or any(
            signal in lowered for signal in self.REQUIREMENT_SIGNALS
        )

    def _segment_line(self, line: str) -> List[str]:
        """Conservatively split a requirement line into atomic requirement phrases.

        Strategy:
        - Split on semicolons first.
        - Split on ' and ' when the clause contains an action verb signal to avoid
          splitting simple enumerations of nouns.
        """
        parts = [p.strip() for p in re.split(r";", line) if p.strip()]
        atomic: List[str] = []
        verbs = [v for v in self.REQUIREMENT_SIGNALS if v.isalpha()]
        for p in parts:
            lowered = p.lower()
            if " and " in lowered and any(v in lowered for v in verbs):
                subparts = [s.strip() for s in re.split(r"\band\b", p) if s.strip()]
                atomic.extend(subparts)
            else:
                atomic.append(p)
        return atomic

    def analyze(self, jd_text: str) -> JobDescription:
        lines = [line.strip() for line in jd_text.splitlines() if line.strip()]
        job_title = None
        company = None
        requirements: List[Requirement] = []
        preferred_section = False
        requirement_section = False

        for raw_line in lines:
            line = raw_line.strip()
            lowered = line.lower()
            if lowered.startswith(("job title:", "role:")):
                job_title = line.split(":", 1)[1].strip()
                continue
            if lowered.startswith("company:"):
                company = line.split(":", 1)[1].strip()
                continue

            if self.HEADING_RE.match(line):
                preferred_section = any(signal in lowered for signal in self.PREFERRED_SIGNALS)
                requirement_section = any(token in lowered for token in (
                    "requirement", "qualification", "responsibilit", "skill", "who you are", "what you"
                ))
                continue

            was_bullet = bool(re.match(r"^[-•*▪–—]\s+", line))
            clean_line = re.sub(r"^[-•*▪–—]\s+", "", line).strip()
            if not self._is_requirement(clean_line, was_bullet, requirement_section):
                continue

            priority = "preferred" if (
                preferred_section or any(signal in clean_line.lower() for signal in self.PREFERRED_SIGNALS)
            ) else "required"

            # Segment long or compound lines into atomic requirements
            segments = self._segment_line(clean_line)
            for seg in segments:
                requirements.append(Requirement(
                    id=f"req_{len(requirements) + 1:03d}",
                    text=seg, category=self._category(seg), priority=priority,
                ))

        return JobDescription(
            job_title=job_title or "Target Role",
            company=company or "Company",
            requirements=requirements,
            keywords=self.extract_keywords_from_text(jd_text),
            raw_text=jd_text,
        )
